mod procfs;
mod runner;
mod session;

use std::io;
use std::path::{Path, PathBuf};

use clap::Parser;
use tracing_appender::non_blocking::WorkerGuard;
use tracing_subscriber::{fmt::writer::Tee, EnvFilter};

#[derive(Debug, Parser)]
#[command(name = "swarmlink-agent", about = "Swarmlink robot agent")]
struct Args {
    /// Agent configuration (TOML) generated by the provisioner.
    #[arg(long)]
    config: PathBuf,
    /// Override the robot id from the config (lets a shared base TOML be
    /// started directly without a per-agent file).
    #[arg(long)]
    robot_id: Option<String>,
    /// Override the agent name (shown in the UI). Overrides the agent TOML's
    /// `name` field; the swarm TOML still wins for pre-defined robots.
    #[arg(long)]
    name: Option<String>,
}

fn setup_logging(name: &str) -> WorkerGuard {
    let filter = EnvFilter::from_default_env();
    std::fs::create_dir_all("logs").ok();

    let ts = chrono::Local::now().format("%Y%m%d-%H%M%S");
    let log_path = Path::new("logs").join(format!("{name}-{ts}.log"));

    let file_appender = tracing_appender::rolling::never("logs", log_path.file_name().unwrap());
    let (file_non_blocking, guard) = tracing_appender::non_blocking(file_appender);
    let (stdout_non_blocking, _) = tracing_appender::non_blocking(io::stdout());

    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_writer(Tee::new(file_non_blocking, stdout_non_blocking))
        .with_ansi(false)
        .init();
    guard
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args = Args::parse();
    let mut cfg = swarmlink_core::AgentConfig::from_toml_path(&args.config)?;
    if let Some(id) = args.robot_id {
        cfg.robot_id = id;
    }
    if let Some(n) = args.name {
        cfg.name = Some(n);
    }
    cfg.validate()?;

    let config_stem = args
        .config
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("agent");
    let _guard = setup_logging(config_stem);

    tracing::info!(
        robot_id = %cfg.robot_id,
        controller = %cfg.controller.endpoint,
        "agent starting"
    );

    session::run_forever(cfg).await
}
