mod procfs;
mod runner;
mod session;

use std::path::PathBuf;

use clap::Parser;
use tracing_subscriber::EnvFilter;

/// Path used when the agent is installed by the provisioner.
const DEFAULT_CONFIG: &str = "/etc/swarm-agent/agent.toml";

#[derive(Debug, Parser)]
#[command(name = "swarmdeck-agent", about = "SwarmDeck robot agent")]
struct Args {
    /// Agent configuration (TOML) generated by the provisioner.
    #[arg(long, default_value = DEFAULT_CONFIG)]
    config: PathBuf,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .init();

    let args = Args::parse();
    let cfg = swarmdeck_core::AgentConfig::from_toml_path(&args.config)?;

    tracing::info!(
        robot_id = %cfg.robot_id,
        controller = %cfg.controller.endpoint,
        "agent starting"
    );

    session::run_forever(cfg).await
}
